### ISSUE TITLE
ValueError: seq_type='protein' contradicts DNA from seq alphabet

### ISSUE THREAD

**Issue by forxhunter** [EPFL-LCSB/etfl#14]
File ".../miniconda3/envs/etfl/lib/python3.7/site-packages/Bio/SeqUtils/__init__.py", line 402, in molecular_weight
    "seq_type=%r contradicts %s from seq alphabet" % (seq_type, tmp_type)
ValueError: seq_type='protein' contradicts DNA from seq alphabet

**Comment by forxhunter** [comment]
```bash
python test_small.py 
Set parameter Username
Academic license - for non-commercial use only - expires 2025-08-14
2024-08-19 13:25:08,089 - ME model - INFO - # ETFL Model ETFL_small_model_T0E1N1_16_enz_64_bins.json initialized
enz. vars:   0%|                                                                                      | 0/1 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "test_small.py", line 5, in <module>
    m = create_etfl_model(0,1)
  File "/data2/2024_Baker'sYeast_WCM/Metabolic_Network_of_Yeast/yETFL/etfl/tutorials/support_test.py", line 1354, in create_etfl_model
    ecoli.add_ribosome(rib,0.2)
  File "/home/tianyu/miniconda3/envs/etfl/lib/python3.7/site-packages/etfl/core/memodel.py", line 1894, in add_ribosome
    self.add_enzymes(ribosome)
  File "/home/tianyu/miniconda3/envs/etfl/lib/python3.7/site-packages/etfl/core/memodel.py", line 1182, in add_enzymes
    self._prep_enzyme_variables(enz)
  File "/home/tianyu/miniconda3/envs/etfl/lib/python3.7/site-packages/etfl/core/memodel.py", line 1091, in _prep_enzyme_variables
    enzyme.init_variable()
  File "/home/tianyu/miniconda3/envs/etfl/lib/python3.7/site-packages/etfl/core/enzyme.py", line 55, in init_variable
    scaling_factor=self.scaling_factor,
  File "/home/tianyu/miniconda3/envs/etfl/lib/python3.7/site-packages/etfl/core/macromolecule.py", line 101, in scaling_factor
    self._scaling_factor = 1/self.molecular_weight
  File "/home/tianyu/miniconda3/envs/etfl/lib/python3.7/site-packages/etfl/core/enzyme.py", line 152, in molecular_weight
    for p, v in self.composition.items())
  File "/home/tianyu/miniconda3/envs/etfl/lib/python3.7/site-packages/etfl/core/enzyme.py", line 152, in <genexpr>
    for p, v in self.composition.items())
  File "/home/tianyu/miniconda3/envs/etfl/lib/python3.7/site-packages/etfl/core/enzyme.py", line 118, in molecular_weight
    return molecular_weight(self.peptide, seq_type='protein') / 1000 # g.mol^-1 -> kg.mol^-1 (SI) = g.mmol^-1
  File "/home/tianyu/miniconda3/envs/etfl/lib/python3.7/site-packages/Bio/SeqUtils/__init__.py", line 402, in molecular_weight
    "seq_type=%r contradicts %s from seq alphabet" % (seq_type, tmp_type)
ValueError: seq_type='protein' contradicts DNA from seq alphabet```

**Comment by forxhunter** [comment]
@psalvy Hi, psalvy, could you please help me checkout why it is in contradiction with DNA from seq alphabet. I just ran the `python test_small.py` under tutorials

**Comment by forxhunter** [comment]
in enzyme.py please update the line 120 from: 
     return molecular_weight(str(self.peptide), 'protein') /1000
            # return molecular_weight(Seq(self., generic_protein)self.peptide, 'protein')

as str() will convert whatever object from that to string, to avoid being initiated as a DNA object
